---
- name: Install Cockpit
  become: true
  ansible.builtin.yum:
    name: cockpit
    state: present

- name: Enable and start Cockpit service
  become: true
  ansible.builtin.systemd:
    name: cockpit
    enabled: true
    state: started

- name: Install cockpit-pcp
  become: true
  ansible.builtin.yum:
    name: cockpit-pcp
    state: present

- name: Enable and start pmlogger service
  become: true
  ansible.builtin.systemd:
    name: pmlogger
    enabled: true
    state: started
