- name: Configure firewalld for Cloudflare-only access
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch Cloudflare IPs
      ansible.builtin.uri:
        url: https://api.cloudflare.com/client/v4/ips
        return_content: yes
      register: cloudflare_ips

    - name: Store Cloudflare IPs in YAML file
      ansible.builtin.copy:
        content: |
            {{ cloudflare_ips.content | to_yaml }}
        dest: vars/cloudflare.yaml
        mode: '0644'